// ═══════════════════════════════════════════════════════════════
//  js/i18n.js — KEY Notes Internationalisation Module
//  Own copy of the Dash Notes i18n engine — same API, independent
//  translation data, so the two apps never touch each other's file.
//  Languages: English (en) · French (fr) · German (de)
//             Greek (el) · Portuguese (pt)
//  Usage:
//    import { initI18n, setLanguage, getLocale, LANG_META } from './i18n.js';
//    initI18n();
//    setLanguage('fr');
//    t('contacts.emptyState');
// ═══════════════════════════════════════════════════════════════

export const LANG_META = {
  en: { flag: '🇬🇧', code: 'EN', locale: 'en-GB' },
  fr: { flag: '🇫🇷', code: 'FR', locale: 'fr-FR' },
  de: { flag: '🇩🇪', code: 'DE', locale: 'de-DE' },
  el: { flag: '🇬🇷', code: 'EL', locale: 'el-GR' },
  pt: { flag: '🇵🇹', code: 'PT', locale: 'pt-PT' },
};

let _lang = localStorage.getItem('key-notes-lang') || 'en';

export function initI18n() {
  _applyTranslations(_lang);
}

export function setLanguage(lang) {
  if (!translations[lang]) return;
  _lang = lang;
  localStorage.setItem('key-notes-lang', lang);
  _applyTranslations(lang);
  window.dispatchEvent(new CustomEvent('key-notes-lang-changed', { detail: lang }));
}

export function getCurrentLang()  { return _lang; }
export function getLocale()       { return LANG_META[_lang]?.locale || 'en-GB'; }
export function getLangMeta()     { return LANG_META[_lang] || LANG_META.en; }

export function t(key) {
  const data = translations[_lang] || translations.en;
  const val  = _getKey(data, key);
  return val !== undefined ? val : (_getKey(translations.en, key) ?? key);
}

export function renderSetupQA(containerId = 'qa-list') {
  const container = document.getElementById(containerId);
  if (!container) return;
  const qa = t('setup.qa');
  if (!Array.isArray(qa)) return;

  container.innerHTML = qa.map((item, i) => {
    const isBestPractice = i === qa.length - 1;
    if (isBestPractice) {
      return `
        <div style="background:rgba(0,229,212,0.06); border:1px solid rgba(0,229,212,0.2);
          border-radius:var(--radius-sm); padding:14px;">
          <p style="font-size:0.85rem; font-weight:700; color:var(--cyan); margin-bottom:6px;">
            ${_esc(item.q)}
          </p>
          <p style="font-size:0.84rem; color:var(--text-secondary); line-height:1.65; margin:0;">
            ${_esc(item.a)}
          </p>
        </div>`;
    }
    return `
      <div>
        <p style="font-size:0.85rem; font-weight:700; color:var(--text-primary); margin-bottom:4px;">
          ${_esc(item.q)}
        </p>
        <p style="font-size:0.84rem; color:var(--text-secondary); line-height:1.65; margin:0;">
          ${_esc(item.a)}
        </p>
      </div>`;
  }).join('');
}

function _getKey(obj, path) {
  return path.split('.').reduce((o, k) => o?.[k], obj);
}

function _esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function _applyTranslations(lang) {
  const data = translations[lang] || translations.en;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const val = _getKey(data, el.getAttribute('data-i18n'));
    if (val !== undefined) el.textContent = val;
  });

  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const val = _getKey(data, el.getAttribute('data-i18n-html'));
    if (val !== undefined) el.innerHTML = val;
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const val = _getKey(data, el.getAttribute('data-i18n-placeholder'));
    if (val !== undefined) el.placeholder = val;
  });

  document.documentElement.lang = lang;
  renderSetupQA('qa-list');
}

// ═══════════════════════════════════════════════════════════════
//  TRANSLATIONS
// ═══════════════════════════════════════════════════════════════
const translations = {

  // ── ENGLISH ───────────────────────────────────────────────────
  en: {
    nav: {
      lock:      'Lock',
      startHere: '<span style="display:block;">About</span><span style="display:block;">&amp; FAQ</span>',
    },
    lock: {
      title:            'KEY Notes',
      subtitle:         'Enter your PIN',
      wrongPin:         'Incorrect PIN — try again',
      forgotPin:        'Forgot PIN?',
      usePassphrase:    'Use passphrase instead',
      useRecovery:      'Use recovery key instead',
      passphraseLabel:  'Master passphrase',
      passphrasePh:     'Enter your master passphrase',
      recoveryLabel:    'Recovery key',
      recoveryPh:       'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
      unlockBtn:        'Unlock',
      backToPin:        'Back to PIN',
      wrongPassphrase:  'Incorrect passphrase',
      wrongRecovery:    'Recovery key not recognised',
      setNewPin:        'Set a new PIN',
      confirmNewPin:    'Confirm new PIN',
      pinResetSuccess:  'PIN updated — use it next time ✅',
    },
    onboard: {
      welcomeTitle:        'Welcome to KEY Notes',
      welcomeDesc:         'A private, encrypted archive for contacts, links, notes, and keys — locked with your own passphrase and PIN. Nothing leaves your device, and nothing is stored in a form anyone but you can read.',
      startBtn:            "Let's set it up",
      step1Title:          'Create a master passphrase',
      step1Desc:           'This is the real key to your data. Choose something you will remember — there is no password reset. Write it down somewhere safe.',
      passphraseLabel:     'Master passphrase',
      passphraseConfirm:   'Confirm passphrase',
      passphraseMismatch:  "Passphrases don't match",
      passphraseTooShort:  'Use at least 10 characters',
      step2Title:          'Choose a PIN',
      step2Desc:           'A quick way to unlock day to day.',
      pinConfirmTitle:     'Confirm your PIN',
      pinMismatch:         "PINs don't match — try again",
      step3Title:          'Your recovery key',
      step3Desc:           'If you ever forget your PIN and your passphrase, this is the only way back in. Save it somewhere safe — a password manager, a printed copy, anywhere but memory.',
      recoveryConfirm:     "I've saved my recovery key",
      emailLabel:          'Email a copy (optional)',
      emailPh:             'you@example.com',
      emailSendBtn:        'Email me a copy',
      emailSent:           'Recovery key emailed ✅',
      emailFailed:         'Could not send email — please save it manually',
      finishBtn:           'Enter KEY Notes',
      continueBtn:         'Continue',
      backBtn:             'Back',
    },
    panel: {
      title:        'About KEY Notes',
      tagline:      'Your private, encrypted archive.',
      desc:         'Contacts, links, notes, and keys — stored locally, encrypted with your own passphrase. Nothing is readable without it, not even by the creators of this app.',
      privacyTitle: 'Privacy',
      privacyText:  'No server. No account. Your data never leaves this device unless you export it yourself.',
    },
    tabs: {
      contacts: 'Contacts',
      links:    'Links',
      archive:  'Archive',
      keys:     'Keys',
    },
    contacts: {
      title:              'Contacts',
      addBtn:             '+ Add Contact',
      searchPh:           'Search contacts…',
      emptyState:         'No contacts yet. Add your first one.',
      labelFirstName:     'First name *',
      labelLastName:      'Last name',
      labelBusiness:      'Business',
      labelPhones:        'Phone numbers',
      addPhoneBtn:        '+ Add another number',
      phoneLabelPh:       'Label (e.g. Mobile, Work)',
      phoneNumberPh:      'Number',
      labelEmail:         'Email',
      labelAddress:       'Address',
      saveBtn:            'Save contact',
      updateBtn:          'Update contact',
      toastSaved:         'Contact saved ✅',
      toastUpdated:       'Contact updated ✅',
      toastDeleted:       'Contact deleted',
      toastNoName:        'Please add at least a first name',
      confirmDelete:      'Delete this contact?',
    },
    links: {
      title:               'Links',
      addBtn:              '+ Add Link',
      searchPh:            'Search links…',
      emptyState:          'No links yet. Add your first one.',
      labelName:           'Name *',
      labelUsername:       'Username',
      labelUrl:            'URL',
      labelPassword:       'Password',
      showPassword:        'Show',
      hidePassword:        'Hide',
      saveBtn:             'Save link',
      updateBtn:           'Update link',
      toastSaved:          'Link saved ✅',
      toastUpdated:        'Link updated ✅',
      toastDeleted:        'Link deleted',
      toastNoName:         'Please add a name',
      toastCopiedPassword: 'Password copied ✅',
      toastCopiedUsername: 'Username copied ✅',
      confirmDelete:       'Delete this link?',
    },
    archive: {
      title:          'Archive',
      addBtn:         '+ Add Note',
      searchPh:       'Search archive…',
      emptyState:     'Nothing archived yet.',
      labelCategory:  'Category *',
      labelTitle:     'Title *',
      labelNote:      'Note',
      notePh:         'Write freely — this field grows with your note, however long it gets…',
      saveBtn:        'Save note',
      updateBtn:      'Update note',
      toastSaved:     'Note saved ✅',
      toastUpdated:   'Note updated ✅',
      toastDeleted:   'Note deleted',
      toastNoTitle:   'Please add a category and title',
      confirmDelete:  'Delete this note?',
    },
    vaultKeys: {
      title:          'Keys',
      addBtn:         '+ Add Key',
      searchPh:       'Search keys…',
      emptyState:     'No keys stored yet.',
      labelTitle:     'Title *',
      labelNote:      'Note',
      notePh:         'Key details, license text, credentials — anything you need to keep close…',
      saveBtn:        'Save key',
      updateBtn:      'Update key',
      toastSaved:     'Key saved ✅',
      toastUpdated:   'Key updated ✅',
      toastDeleted:   'Key deleted',
      toastNoTitle:   'Please add a title',
      confirmDelete:  'Delete this key?',
    },
    common: {
      view: 'View', edit: 'Edit', copy: 'Copy', save: 'Save',
      delete: 'Delete', close: 'Close', cancel: 'Cancel',
      copiedGeneric: 'Copied ✅',
    },
    settings: {
      title:               'Settings',
      backupTitle:         'Backup & Restore',
      backupDesc:          'Your data stays encrypted in the exported file — it can only be opened again inside KEY Notes, with your passphrase or PIN.',
      downloadBtn:         'Download encrypted backup',
      restoreBtn:          'Restore from backup',
      toastDownloaded:     'Encrypted backup downloaded ✅',
      toastRestored:       'Backup restored ✅',
      toastRestoreFailed:  'Restore failed — check the file and try again',
      securityTitle:       'Security',
      changePinBtn:        'Change PIN',
      changePassphraseBtn: 'Change passphrase',
      viewRecoveryBtn:     'Generate new recovery key',
      recoveryWarning:     'This replaces your old recovery key — the old one will stop working.',
      lockNowBtn:          'Lock now',
      langTitle:           'Language',
    },
    setup: {
      title:    'About & FAQ',
      subtitle: 'How KEY Notes keeps your archive private.',
      qaBtn:    'Q & A',
      qaTitle:  'Questions & Answers',
      closeBtn: 'Close',
      leaveBtn: 'Leave',
      qa: [
        { q: 'Where is my data stored?',
          a: 'Entirely on this device, in your browser\'s local storage — encrypted. Nothing is sent to any server, including by the creators of this app.' },
        { q: 'What happens if I forget my PIN?',
          a: 'Unlock with your master passphrase instead, then set a new PIN from Settings.' },
        { q: 'What happens if I forget my passphrase too?',
          a: 'Use your recovery key — it was shown once during setup. If you\'ve lost that too, the data cannot be recovered. That\'s the tradeoff of real encryption.' },
        { q: 'Can I use KEY Notes on more than one device?',
          a: 'Each device keeps its own separate, encrypted data. Use Settings → Download encrypted backup on one device, then Restore from backup on the other, using the same passphrase or PIN.' },
        { q: 'What does "encrypted backup" actually mean?',
          a: 'The exported file is unreadable without your passphrase or PIN — even if someone else opens it, they see scrambled data, not your contacts or passwords.' },
        { q: 'Does clearing my browser data delete everything?',
          a: 'Yes — permanently. Download a backup regularly from Settings.' },
        { q: 'Best Practice — staying safe',
          a: 'Save your recovery key somewhere outside this device — a password manager or a printed copy. Download a backup after any big update to your archive.' },
      ],
    },
  },

  // ── FRENCH ───────────────────────────────────────────────────
  fr: {
    nav: {
      lock:      'Verrouiller',
      startHere: '<span style="display:block;">À propos</span><span style="display:block;">&amp; FAQ</span>',
    },
    lock: {
      title:            'KEY Notes',
      subtitle:         'Entrez votre code PIN',
      wrongPin:         'Code PIN incorrect — réessayez',
      forgotPin:        'PIN oublié ?',
      usePassphrase:    'Utiliser la phrase secrète',
      useRecovery:      'Utiliser la clé de récupération',
      passphraseLabel:  'Phrase secrète principale',
      passphrasePh:     'Entrez votre phrase secrète',
      recoveryLabel:    'Clé de récupération',
      recoveryPh:       'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
      unlockBtn:        'Déverrouiller',
      backToPin:        'Retour au PIN',
      wrongPassphrase:  'Phrase secrète incorrecte',
      wrongRecovery:    'Clé de récupération non reconnue',
      setNewPin:        'Définir un nouveau PIN',
      confirmNewPin:    'Confirmer le nouveau PIN',
      pinResetSuccess:  'PIN mis à jour ✅',
    },
    onboard: {
      welcomeTitle:        'Bienvenue sur KEY Notes',
      welcomeDesc:         'Une archive privée et chiffrée pour vos contacts, liens, notes et clés — protégée par votre propre phrase secrète et code PIN. Rien ne quitte votre appareil.',
      startBtn:            'Configurer maintenant',
      step1Title:          'Créez une phrase secrète principale',
      step1Desc:           'C\'est la véritable clé de vos données. Choisissez quelque chose de mémorable — il n\'y a pas de réinitialisation. Notez-la en lieu sûr.',
      passphraseLabel:     'Phrase secrète principale',
      passphraseConfirm:   'Confirmer la phrase secrète',
      passphraseMismatch:  'Les phrases secrètes ne correspondent pas',
      passphraseTooShort:  'Utilisez au moins 10 caractères',
      step2Title:          'Choisissez un code PIN',
      step2Desc:           'Un moyen rapide de déverrouiller au quotidien.',
      pinConfirmTitle:     'Confirmez votre PIN',
      pinMismatch:         'Les PIN ne correspondent pas — réessayez',
      step3Title:          'Votre clé de récupération',
      step3Desc:           'Si vous oubliez votre PIN et votre phrase secrète, c\'est votre seul moyen de récupérer l\'accès. Conservez-la en lieu sûr.',
      recoveryConfirm:     'J\'ai sauvegardé ma clé de récupération',
      emailLabel:          'Envoyer une copie par e-mail (facultatif)',
      emailPh:             'vous@exemple.com',
      emailSendBtn:        'M\'envoyer une copie',
      emailSent:           'Clé de récupération envoyée ✅',
      emailFailed:         'Envoi impossible — sauvegardez-la manuellement',
      finishBtn:           'Entrer dans KEY Notes',
      continueBtn:         'Continuer',
      backBtn:             'Retour',
    },
    panel: {
      title:        'À propos de KEY Notes',
      tagline:      'Votre archive privée et chiffrée.',
      desc:         'Contacts, liens, notes et clés — stockés localement, chiffrés avec votre propre phrase secrète. Illisibles sans elle, même par les créateurs de cette application.',
      privacyTitle: 'Confidentialité',
      privacyText:  'Aucun serveur. Aucun compte. Vos données ne quittent jamais cet appareil sauf si vous les exportez vous-même.',
    },
    tabs: {
      contacts: 'Contacts',
      links:    'Liens',
      archive:  'Archives',
      keys:     'Clés',
    },
    contacts: {
      title:          'Contacts',
      addBtn:         '+ Ajouter un contact',
      searchPh:       'Rechercher des contacts…',
      emptyState:     'Aucun contact pour le moment.',
      labelFirstName: 'Prénom *',
      labelLastName:  'Nom',
      labelBusiness:  'Entreprise',
      labelPhones:    'Numéros de téléphone',
      addPhoneBtn:    '+ Ajouter un numéro',
      phoneLabelPh:   'Libellé (ex. Mobile, Travail)',
      phoneNumberPh:  'Numéro',
      labelEmail:     'E-mail',
      labelAddress:   'Adresse',
      saveBtn:        'Enregistrer le contact',
      updateBtn:      'Mettre à jour le contact',
      toastSaved:     'Contact enregistré ✅',
      toastUpdated:   'Contact mis à jour ✅',
      toastDeleted:   'Contact supprimé',
      toastNoName:    'Ajoutez au moins un prénom',
      confirmDelete:  'Supprimer ce contact ?',
    },
    links: {
      title:               'Liens',
      addBtn:              '+ Ajouter un lien',
      searchPh:            'Rechercher des liens…',
      emptyState:          'Aucun lien pour le moment.',
      labelName:           'Nom *',
      labelUsername:       'Identifiant',
      labelUrl:            'URL',
      labelPassword:       'Mot de passe',
      showPassword:        'Afficher',
      hidePassword:        'Masquer',
      saveBtn:             'Enregistrer le lien',
      updateBtn:           'Mettre à jour le lien',
      toastSaved:          'Lien enregistré ✅',
      toastUpdated:        'Lien mis à jour ✅',
      toastDeleted:        'Lien supprimé',
      toastNoName:         'Ajoutez un nom',
      toastCopiedPassword: 'Mot de passe copié ✅',
      toastCopiedUsername: 'Identifiant copié ✅',
      confirmDelete:       'Supprimer ce lien ?',
    },
    archive: {
      title:          'Archives',
      addBtn:         '+ Ajouter une note',
      searchPh:       'Rechercher dans les archives…',
      emptyState:     'Rien d\'archivé pour le moment.',
      labelCategory:  'Catégorie *',
      labelTitle:     'Titre *',
      labelNote:      'Note',
      notePh:         'Écrivez librement — ce champ s\'agrandit avec votre note…',
      saveBtn:        'Enregistrer la note',
      updateBtn:      'Mettre à jour la note',
      toastSaved:     'Note enregistrée ✅',
      toastUpdated:   'Note mise à jour ✅',
      toastDeleted:   'Note supprimée',
      toastNoTitle:   'Ajoutez une catégorie et un titre',
      confirmDelete:  'Supprimer cette note ?',
    },
    vaultKeys: {
      title:          'Clés',
      addBtn:         '+ Ajouter une clé',
      searchPh:       'Rechercher des clés…',
      emptyState:     'Aucune clé enregistrée.',
      labelTitle:     'Titre *',
      labelNote:      'Note',
      notePh:         'Détails de licence, identifiants — tout ce que vous devez garder à portée…',
      saveBtn:        'Enregistrer la clé',
      updateBtn:      'Mettre à jour la clé',
      toastSaved:     'Clé enregistrée ✅',
      toastUpdated:   'Clé mise à jour ✅',
      toastDeleted:   'Clé supprimée',
      toastNoTitle:   'Ajoutez un titre',
      confirmDelete:  'Supprimer cette clé ?',
    },
    common: {
      view: 'Voir', edit: 'Modifier', copy: 'Copier', save: 'Enregistrer',
      delete: 'Supprimer', close: 'Fermer', cancel: 'Annuler',
      copiedGeneric: 'Copié ✅',
    },
    settings: {
      title:               'Réglages',
      backupTitle:         'Sauvegarde & Restauration',
      backupDesc:          'Vos données restent chiffrées dans le fichier exporté — il ne peut être ouvert que dans KEY Notes, avec votre phrase secrète ou PIN.',
      downloadBtn:         'Télécharger une sauvegarde chiffrée',
      restoreBtn:          'Restaurer depuis une sauvegarde',
      toastDownloaded:     'Sauvegarde chiffrée téléchargée ✅',
      toastRestored:       'Sauvegarde restaurée ✅',
      toastRestoreFailed:  'Échec de la restauration — vérifiez le fichier',
      securityTitle:       'Sécurité',
      changePinBtn:        'Changer le PIN',
      changePassphraseBtn: 'Changer la phrase secrète',
      viewRecoveryBtn:     'Générer une nouvelle clé de récupération',
      recoveryWarning:     'Cela remplace votre ancienne clé de récupération — l\'ancienne cessera de fonctionner.',
      lockNowBtn:          'Verrouiller maintenant',
      langTitle:           'Langue',
    },
    setup: {
      title:    'À propos & FAQ',
      subtitle: 'Comment KEY Notes protège votre archive.',
      qaBtn:    'Q & R',
      qaTitle:  'Questions & Réponses',
      closeBtn: 'Fermer',
      leaveBtn: 'Quitter',
      qa: [
        { q: 'Où sont stockées mes données ?',
          a: 'Entièrement sur cet appareil, dans le stockage local de votre navigateur — chiffrées. Rien n\'est envoyé à un serveur.' },
        { q: 'Que se passe-t-il si j\'oublie mon PIN ?',
          a: 'Déverrouillez avec votre phrase secrète, puis définissez un nouveau PIN depuis les Réglages.' },
        { q: 'Et si j\'oublie aussi ma phrase secrète ?',
          a: 'Utilisez votre clé de récupération, affichée une seule fois lors de la configuration. Si vous l\'avez perdue aussi, les données sont irrécupérables.' },
        { q: 'Puis-je utiliser KEY Notes sur plusieurs appareils ?',
          a: 'Chaque appareil conserve ses propres données chiffrées. Utilisez Réglages → Télécharger une sauvegarde chiffrée, puis Restaurer sur l\'autre appareil.' },
        { q: 'Que signifie "sauvegarde chiffrée" ?',
          a: 'Le fichier exporté est illisible sans votre phrase secrète ou PIN.' },
        { q: 'Effacer les données du navigateur supprime-t-il tout ?',
          a: 'Oui, définitivement. Téléchargez une sauvegarde régulièrement.' },
        { q: 'Bonnes pratiques',
          a: 'Conservez votre clé de récupération hors de cet appareil. Téléchargez une sauvegarde après chaque mise à jour importante.' },
      ],
    },
  },

  // ── GERMAN ───────────────────────────────────────────────────
  de: {
    nav: {
      lock:      'Sperren',
      startHere: '<span style="display:block;">Info</span><span style="display:block;">&amp; FAQ</span>',
    },
    lock: {
      title:            'KEY Notes',
      subtitle:         'PIN eingeben',
      wrongPin:         'Falscher PIN — erneut versuchen',
      forgotPin:        'PIN vergessen?',
      usePassphrase:    'Passphrase verwenden',
      useRecovery:      'Wiederherstellungsschlüssel verwenden',
      passphraseLabel:  'Master-Passphrase',
      passphrasePh:     'Passphrase eingeben',
      recoveryLabel:    'Wiederherstellungsschlüssel',
      recoveryPh:       'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
      unlockBtn:        'Entsperren',
      backToPin:        'Zurück zum PIN',
      wrongPassphrase:  'Falsche Passphrase',
      wrongRecovery:    'Schlüssel nicht erkannt',
      setNewPin:        'Neuen PIN festlegen',
      confirmNewPin:    'Neuen PIN bestätigen',
      pinResetSuccess:  'PIN aktualisiert ✅',
    },
    onboard: {
      welcomeTitle:        'Willkommen bei KEY Notes',
      welcomeDesc:         'Ein privates, verschlüsseltes Archiv für Kontakte, Links, Notizen und Schlüssel — gesichert mit Ihrer eigenen Passphrase und PIN.',
      startBtn:            'Jetzt einrichten',
      step1Title:          'Master-Passphrase erstellen',
      step1Desc:           'Dies ist der eigentliche Schlüssel zu Ihren Daten. Wählen Sie etwas Merkfähiges — es gibt kein Zurücksetzen. Notieren Sie sie sicher.',
      passphraseLabel:     'Master-Passphrase',
      passphraseConfirm:   'Passphrase bestätigen',
      passphraseMismatch:  'Passphrasen stimmen nicht überein',
      passphraseTooShort:  'Mindestens 10 Zeichen verwenden',
      step2Title:          'PIN wählen',
      step2Desc:           'Ein schneller Weg zum täglichen Entsperren.',
      pinConfirmTitle:     'PIN bestätigen',
      pinMismatch:         'PINs stimmen nicht überein',
      step3Title:          'Ihr Wiederherstellungsschlüssel',
      step3Desc:           'Falls Sie PIN und Passphrase vergessen, ist dies der einzige Weg zurück. Sicher aufbewahren.',
      recoveryConfirm:     'Ich habe meinen Schlüssel gespeichert',
      emailLabel:          'Kopie per E-Mail senden (optional)',
      emailPh:             'sie@beispiel.com',
      emailSendBtn:        'Kopie senden',
      emailSent:           'Wiederherstellungsschlüssel gesendet ✅',
      emailFailed:         'Versand fehlgeschlagen — bitte manuell speichern',
      finishBtn:           'KEY Notes öffnen',
      continueBtn:         'Weiter',
      backBtn:             'Zurück',
    },
    panel: {
      title:        'Über KEY Notes',
      tagline:      'Ihr privates, verschlüsseltes Archiv.',
      desc:         'Kontakte, Links, Notizen und Schlüssel — lokal gespeichert, mit Ihrer eigenen Passphrase verschlüsselt.',
      privacyTitle: 'Datenschutz',
      privacyText:  'Kein Server. Kein Konto. Ihre Daten verlassen dieses Gerät nie, außer Sie exportieren sie selbst.',
    },
    tabs: {
      contacts: 'Kontakte',
      links:    'Links',
      archive:  'Archiv',
      keys:     'Schlüssel',
    },
    contacts: {
      title:          'Kontakte',
      addBtn:         '+ Kontakt hinzufügen',
      searchPh:       'Kontakte suchen…',
      emptyState:     'Noch keine Kontakte.',
      labelFirstName: 'Vorname *',
      labelLastName:  'Nachname',
      labelBusiness:  'Unternehmen',
      labelPhones:    'Telefonnummern',
      addPhoneBtn:    '+ Weitere Nummer',
      phoneLabelPh:   'Bezeichnung (z. B. Mobil, Arbeit)',
      phoneNumberPh:  'Nummer',
      labelEmail:     'E-Mail',
      labelAddress:   'Adresse',
      saveBtn:        'Kontakt speichern',
      updateBtn:      'Kontakt aktualisieren',
      toastSaved:     'Kontakt gespeichert ✅',
      toastUpdated:   'Kontakt aktualisiert ✅',
      toastDeleted:   'Kontakt gelöscht',
      toastNoName:    'Bitte mindestens einen Vornamen angeben',
      confirmDelete:  'Diesen Kontakt löschen?',
    },
    links: {
      title:               'Links',
      addBtn:              '+ Link hinzufügen',
      searchPh:            'Links suchen…',
      emptyState:          'Noch keine Links.',
      labelName:           'Name *',
      labelUsername:       'Benutzername',
      labelUrl:            'URL',
      labelPassword:       'Passwort',
      showPassword:        'Anzeigen',
      hidePassword:        'Verbergen',
      saveBtn:             'Link speichern',
      updateBtn:           'Link aktualisieren',
      toastSaved:          'Link gespeichert ✅',
      toastUpdated:        'Link aktualisiert ✅',
      toastDeleted:        'Link gelöscht',
      toastNoName:         'Bitte einen Namen angeben',
      toastCopiedPassword: 'Passwort kopiert ✅',
      toastCopiedUsername: 'Benutzername kopiert ✅',
      confirmDelete:       'Diesen Link löschen?',
    },
    archive: {
      title:          'Archiv',
      addBtn:         '+ Notiz hinzufügen',
      searchPh:       'Archiv durchsuchen…',
      emptyState:     'Noch nichts archiviert.',
      labelCategory:  'Kategorie *',
      labelTitle:     'Titel *',
      labelNote:      'Notiz',
      notePh:         'Frei schreiben — dieses Feld wächst mit Ihrer Notiz…',
      saveBtn:        'Notiz speichern',
      updateBtn:      'Notiz aktualisieren',
      toastSaved:     'Notiz gespeichert ✅',
      toastUpdated:   'Notiz aktualisiert ✅',
      toastDeleted:   'Notiz gelöscht',
      toastNoTitle:   'Bitte Kategorie und Titel angeben',
      confirmDelete:  'Diese Notiz löschen?',
    },
    vaultKeys: {
      title:          'Schlüssel',
      addBtn:         '+ Schlüssel hinzufügen',
      searchPh:       'Schlüssel suchen…',
      emptyState:     'Noch keine Schlüssel gespeichert.',
      labelTitle:     'Titel *',
      labelNote:      'Notiz',
      notePh:         'Lizenzdetails, Zugangsdaten — alles, was griffbereit sein soll…',
      saveBtn:        'Schlüssel speichern',
      updateBtn:      'Schlüssel aktualisieren',
      toastSaved:     'Schlüssel gespeichert ✅',
      toastUpdated:   'Schlüssel aktualisiert ✅',
      toastDeleted:   'Schlüssel gelöscht',
      toastNoTitle:   'Bitte einen Titel angeben',
      confirmDelete:  'Diesen Schlüssel löschen?',
    },
    common: {
      view: 'Ansehen', edit: 'Bearbeiten', copy: 'Kopieren', save: 'Speichern',
      delete: 'Löschen', close: 'Schließen', cancel: 'Abbrechen',
      copiedGeneric: 'Kopiert ✅',
    },
    settings: {
      title:               'Einstellungen',
      backupTitle:         'Sichern & Wiederherstellen',
      backupDesc:          'Ihre Daten bleiben in der exportierten Datei verschlüsselt — nur mit Ihrer Passphrase oder PIN in KEY Notes wieder zu öffnen.',
      downloadBtn:         'Verschlüsseltes Backup herunterladen',
      restoreBtn:          'Aus Backup wiederherstellen',
      toastDownloaded:     'Verschlüsseltes Backup heruntergeladen ✅',
      toastRestored:       'Backup wiederhergestellt ✅',
      toastRestoreFailed:  'Wiederherstellung fehlgeschlagen — Datei prüfen',
      securityTitle:       'Sicherheit',
      changePinBtn:        'PIN ändern',
      changePassphraseBtn: 'Passphrase ändern',
      viewRecoveryBtn:     'Neuen Wiederherstellungsschlüssel erzeugen',
      recoveryWarning:     'Dies ersetzt Ihren alten Schlüssel — der alte funktioniert danach nicht mehr.',
      lockNowBtn:          'Jetzt sperren',
      langTitle:           'Sprache',
    },
    setup: {
      title:    'Info & FAQ',
      subtitle: 'Wie KEY Notes Ihr Archiv privat hält.',
      qaBtn:    'F & A',
      qaTitle:  'Fragen & Antworten',
      closeBtn: 'Schließen',
      leaveBtn: 'Verlassen',
      qa: [
        { q: 'Wo werden meine Daten gespeichert?',
          a: 'Vollständig auf diesem Gerät, im lokalen Speicher Ihres Browsers — verschlüsselt. Nichts wird an einen Server gesendet.' },
        { q: 'Was passiert, wenn ich meinen PIN vergesse?',
          a: 'Entsperren Sie mit Ihrer Passphrase und legen Sie dann in den Einstellungen einen neuen PIN fest.' },
        { q: 'Und wenn ich auch meine Passphrase vergesse?',
          a: 'Nutzen Sie Ihren Wiederherstellungsschlüssel, der einmalig bei der Einrichtung angezeigt wurde. Ist auch dieser verloren, sind die Daten nicht wiederherstellbar.' },
        { q: 'Kann ich KEY Notes auf mehreren Geräten nutzen?',
          a: 'Jedes Gerät hat eigene, verschlüsselte Daten. Nutzen Sie Einstellungen → Backup herunterladen, dann auf dem anderen Gerät wiederherstellen.' },
        { q: 'Was bedeutet "verschlüsseltes Backup"?',
          a: 'Die exportierte Datei ist ohne Ihre Passphrase oder PIN unlesbar.' },
        { q: 'Löscht das Leeren der Browserdaten alles?',
          a: 'Ja, dauerhaft. Laden Sie regelmäßig ein Backup herunter.' },
        { q: 'Bewährte Praxis',
          a: 'Bewahren Sie Ihren Wiederherstellungsschlüssel außerhalb dieses Geräts auf. Laden Sie nach größeren Änderungen ein Backup herunter.' },
      ],
    },
  },

  // ── GREEK ────────────────────────────────────────────────────
  el: {
    nav: {
      lock:      'Κλείδωμα',
      startHere: '<span style="display:block;">Σχετικά</span><span style="display:block;">&amp; Ερωτήσεις</span>',
    },
    lock: {
      title:            'KEY Notes',
      subtitle:         'Εισάγετε το PIN σας',
      wrongPin:         'Λανθασμένο PIN — δοκιμάστε ξανά',
      forgotPin:        'Ξεχάσατε το PIN;',
      usePassphrase:    'Χρήση φράσης-κλειδί',
      useRecovery:      'Χρήση κλειδιού ανάκτησης',
      passphraseLabel:  'Κύρια φράση-κλειδί',
      passphrasePh:     'Εισάγετε τη φράση-κλειδί σας',
      recoveryLabel:    'Κλειδί ανάκτησης',
      recoveryPh:       'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
      unlockBtn:        'Ξεκλείδωμα',
      backToPin:        'Επιστροφή στο PIN',
      wrongPassphrase:  'Λανθασμένη φράση-κλειδί',
      wrongRecovery:    'Το κλειδί δεν αναγνωρίστηκε',
      setNewPin:        'Ορισμός νέου PIN',
      confirmNewPin:    'Επιβεβαίωση νέου PIN',
      pinResetSuccess:  'Το PIN ενημερώθηκε ✅',
    },
    onboard: {
      welcomeTitle:        'Καλώς ήρθατε στο KEY Notes',
      welcomeDesc:         'Ένα ιδιωτικό, κρυπτογραφημένο αρχείο για επαφές, συνδέσμους, σημειώσεις και κλειδιά — κλειδωμένο με τη δική σας φράση-κλειδί και PIN.',
      startBtn:            'Ρύθμιση τώρα',
      step1Title:          'Δημιουργήστε μια κύρια φράση-κλειδί',
      step1Desc:           'Αυτό είναι το πραγματικό κλειδί των δεδομένων σας. Επιλέξτε κάτι που θα θυμάστε — δεν υπάρχει επαναφορά. Σημειώστε την κάπου ασφαλές.',
      passphraseLabel:     'Κύρια φράση-κλειδί',
      passphraseConfirm:   'Επιβεβαίωση φράσης-κλειδί',
      passphraseMismatch:  'Οι φράσεις δεν ταιριάζουν',
      passphraseTooShort:  'Χρησιμοποιήστε τουλάχιστον 10 χαρακτήρες',
      step2Title:          'Επιλέξτε PIN',
      step2Desc:           'Ένας γρήγορος τρόπος καθημερινού ξεκλειδώματος.',
      pinConfirmTitle:     'Επιβεβαιώστε το PIN σας',
      pinMismatch:         'Τα PIN δεν ταιριάζουν — δοκιμάστε ξανά',
      step3Title:          'Το κλειδί ανάκτησής σας',
      step3Desc:           'Αν ξεχάσετε ποτέ το PIN και τη φράση-κλειδί, αυτός είναι ο μόνος τρόπος επιστροφής. Φυλάξτε το ασφαλές.',
      recoveryConfirm:     'Αποθήκευσα το κλειδί ανάκτησης',
      emailLabel:          'Αποστολή αντιγράφου με email (προαιρετικό)',
      emailPh:             'you@example.com',
      emailSendBtn:        'Στείλτε μου αντίγραφο',
      emailSent:           'Το κλειδί ανάκτησης στάλθηκε ✅',
      emailFailed:         'Αποτυχία αποστολής — αποθηκεύστε το χειροκίνητα',
      finishBtn:           'Είσοδος στο KEY Notes',
      continueBtn:         'Συνέχεια',
      backBtn:             'Πίσω',
    },
    panel: {
      title:        'Σχετικά με το KEY Notes',
      tagline:      'Το ιδιωτικό, κρυπτογραφημένο αρχείο σας.',
      desc:         'Επαφές, σύνδεσμοι, σημειώσεις και κλειδιά — αποθηκευμένα τοπικά, κρυπτογραφημένα με τη δική σας φράση-κλειδί.',
      privacyTitle: 'Απόρρητο',
      privacyText:  'Χωρίς διακομιστή. Χωρίς λογαριασμό. Τα δεδομένα σας δεν φεύγουν ποτέ από αυτή τη συσκευή.',
    },
    tabs: {
      contacts: 'Επαφές',
      links:    'Σύνδεσμοι',
      archive:  'Αρχείο',
      keys:     'Κλειδιά',
    },
    contacts: {
      title:          'Επαφές',
      addBtn:         '+ Προσθήκη επαφής',
      searchPh:       'Αναζήτηση επαφών…',
      emptyState:     'Δεν υπάρχουν επαφές ακόμα.',
      labelFirstName: 'Όνομα *',
      labelLastName:  'Επώνυμο',
      labelBusiness:  'Επιχείρηση',
      labelPhones:    'Τηλέφωνα',
      addPhoneBtn:    '+ Προσθήκη αριθμού',
      phoneLabelPh:   'Ετικέτα (π.χ. Κινητό, Εργασία)',
      phoneNumberPh:  'Αριθμός',
      labelEmail:     'Email',
      labelAddress:   'Διεύθυνση',
      saveBtn:        'Αποθήκευση επαφής',
      updateBtn:      'Ενημέρωση επαφής',
      toastSaved:     'Η επαφή αποθηκεύτηκε ✅',
      toastUpdated:   'Η επαφή ενημερώθηκε ✅',
      toastDeleted:   'Η επαφή διαγράφηκε',
      toastNoName:    'Προσθέστε τουλάχιστον ένα όνομα',
      confirmDelete:  'Διαγραφή αυτής της επαφής;',
    },
    links: {
      title:               'Σύνδεσμοι',
      addBtn:              '+ Προσθήκη συνδέσμου',
      searchPh:            'Αναζήτηση συνδέσμων…',
      emptyState:          'Δεν υπάρχουν σύνδεσμοι ακόμα.',
      labelName:           'Όνομα *',
      labelUsername:       'Όνομα χρήστη',
      labelUrl:            'URL',
      labelPassword:       'Κωδικός πρόσβασης',
      showPassword:        'Εμφάνιση',
      hidePassword:        'Απόκρυψη',
      saveBtn:             'Αποθήκευση συνδέσμου',
      updateBtn:           'Ενημέρωση συνδέσμου',
      toastSaved:          'Ο σύνδεσμος αποθηκεύτηκε ✅',
      toastUpdated:        'Ο σύνδεσμος ενημερώθηκε ✅',
      toastDeleted:        'Ο σύνδεσμος διαγράφηκε',
      toastNoName:         'Προσθέστε ένα όνομα',
      toastCopiedPassword: 'Ο κωδικός αντιγράφηκε ✅',
      toastCopiedUsername: 'Το όνομα χρήστη αντιγράφηκε ✅',
      confirmDelete:       'Διαγραφή αυτού του συνδέσμου;',
    },
    archive: {
      title:          'Αρχείο',
      addBtn:         '+ Προσθήκη σημείωσης',
      searchPh:       'Αναζήτηση στο αρχείο…',
      emptyState:     'Δεν υπάρχει τίποτα αρχειοθετημένο ακόμα.',
      labelCategory:  'Κατηγορία *',
      labelTitle:     'Τίτλος *',
      labelNote:      'Σημείωση',
      notePh:         'Γράψτε ελεύθερα — αυτό το πεδίο μεγαλώνει με τη σημείωσή σας…',
      saveBtn:        'Αποθήκευση σημείωσης',
      updateBtn:      'Ενημέρωση σημείωσης',
      toastSaved:     'Η σημείωση αποθηκεύτηκε ✅',
      toastUpdated:   'Η σημείωση ενημερώθηκε ✅',
      toastDeleted:   'Η σημείωση διαγράφηκε',
      toastNoTitle:   'Προσθέστε κατηγορία και τίτλο',
      confirmDelete:  'Διαγραφή αυτής της σημείωσης;',
    },
    vaultKeys: {
      title:          'Κλειδιά',
      addBtn:         '+ Προσθήκη κλειδιού',
      searchPh:       'Αναζήτηση κλειδιών…',
      emptyState:     'Δεν υπάρχουν αποθηκευμένα κλειδιά.',
      labelTitle:     'Τίτλος *',
      labelNote:      'Σημείωση',
      notePh:         'Στοιχεία άδειας, διαπιστευτήρια — ό,τι χρειάζεται να έχετε κοντά…',
      saveBtn:        'Αποθήκευση κλειδιού',
      updateBtn:      'Ενημέρωση κλειδιού',
      toastSaved:     'Το κλειδί αποθηκεύτηκε ✅',
      toastUpdated:   'Το κλειδί ενημερώθηκε ✅',
      toastDeleted:   'Το κλειδί διαγράφηκε',
      toastNoTitle:   'Προσθέστε έναν τίτλο',
      confirmDelete:  'Διαγραφή αυτού του κλειδιού;',
    },
    common: {
      view: 'Προβολή', edit: 'Επεξεργασία', copy: 'Αντιγραφή', save: 'Αποθήκευση',
      delete: 'Διαγραφή', close: 'Κλείσιμο', cancel: 'Ακύρωση',
      copiedGeneric: 'Αντιγράφηκε ✅',
    },
    settings: {
      title:               'Ρυθμίσεις',
      backupTitle:         'Αντίγραφο & Επαναφορά',
      backupDesc:          'Τα δεδομένα σας παραμένουν κρυπτογραφημένα στο εξαγόμενο αρχείο — ανοίγει μόνο μέσα στο KEY Notes, με τη φράση-κλειδί ή το PIN σας.',
      downloadBtn:         'Λήψη κρυπτογραφημένου αντιγράφου',
      restoreBtn:          'Επαναφορά από αντίγραφο',
      toastDownloaded:     'Το κρυπτογραφημένο αντίγραφο κατέβηκε ✅',
      toastRestored:       'Το αντίγραφο επαναφέρθηκε ✅',
      toastRestoreFailed:  'Η επαναφορά απέτυχε — ελέγξτε το αρχείο',
      securityTitle:       'Ασφάλεια',
      changePinBtn:        'Αλλαγή PIN',
      changePassphraseBtn: 'Αλλαγή φράσης-κλειδί',
      viewRecoveryBtn:     'Δημιουργία νέου κλειδιού ανάκτησης',
      recoveryWarning:     'Αυτό αντικαθιστά το παλιό κλειδί ανάκτησης — το παλιό θα πάψει να λειτουργεί.',
      lockNowBtn:          'Κλείδωμα τώρα',
      langTitle:           'Γλώσσα',
    },
    setup: {
      title:    'Σχετικά & Ερωτήσεις',
      subtitle: 'Πώς το KEY Notes κρατά το αρχείο σας ιδιωτικό.',
      qaBtn:    'Ε & Α',
      qaTitle:  'Ερωτήσεις & Απαντήσεις',
      closeBtn: 'Κλείσιμο',
      leaveBtn: 'Έξοδος',
      qa: [
        { q: 'Πού αποθηκεύονται τα δεδομένα μου;',
          a: 'Εξ ολοκλήρου σε αυτή τη συσκευή, στον τοπικό χώρο αποθήκευσης του προγράμματος περιήγησης — κρυπτογραφημένα. Τίποτα δεν στέλνεται σε διακομιστή.' },
        { q: 'Τι γίνεται αν ξεχάσω το PIN μου;',
          a: 'Ξεκλειδώστε με τη φράση-κλειδί σας, μετά ορίστε νέο PIN από τις Ρυθμίσεις.' },
        { q: 'Τι γίνεται αν ξεχάσω και τη φράση-κλειδί;',
          a: 'Χρησιμοποιήστε το κλειδί ανάκτησης που εμφανίστηκε μία φορά κατά τη ρύθμιση. Αν το χάσατε κι αυτό, τα δεδομένα δεν ανακτώνται.' },
        { q: 'Μπορώ να χρησιμοποιήσω το KEY Notes σε περισσότερες συσκευές;',
          a: 'Κάθε συσκευή έχει τα δικά της κρυπτογραφημένα δεδομένα. Χρησιμοποιήστε Ρυθμίσεις → Λήψη αντιγράφου, μετά Επαναφορά στην άλλη συσκευή.' },
        { q: 'Τι σημαίνει "κρυπτογραφημένο αντίγραφο";',
          a: 'Το εξαγόμενο αρχείο είναι δυσανάγνωστο χωρίς τη φράση-κλειδί ή το PIN σας.' },
        { q: 'Η εκκαθάριση δεδομένων του προγράμματος περιήγησης διαγράφει τα πάντα;',
          a: 'Ναι, μόνιμα. Κατεβάστε τακτικά ένα αντίγραφο.' },
        { q: 'Βέλτιστη πρακτική',
          a: 'Φυλάξτε το κλειδί ανάκτησης εκτός αυτής της συσκευής. Κατεβάστε αντίγραφο μετά από κάθε σημαντική ενημέρωση.' },
      ],
    },
  },

  // ── PORTUGUESE ───────────────────────────────────────────────
  pt: {
    nav: {
      lock:      'Bloquear',
      startHere: '<span style="display:block;">Sobre</span><span style="display:block;">&amp; FAQ</span>',
    },
    lock: {
      title:            'KEY Notes',
      subtitle:         'Introduz o teu PIN',
      wrongPin:         'PIN incorreto — tenta novamente',
      forgotPin:        'Esqueceste o PIN?',
      usePassphrase:    'Usar frase-passe',
      useRecovery:      'Usar chave de recuperação',
      passphraseLabel:  'Frase-passe principal',
      passphrasePh:     'Introduz a tua frase-passe',
      recoveryLabel:    'Chave de recuperação',
      recoveryPh:       'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX',
      unlockBtn:        'Desbloquear',
      backToPin:        'Voltar ao PIN',
      wrongPassphrase:  'Frase-passe incorreta',
      wrongRecovery:    'Chave não reconhecida',
      setNewPin:        'Definir novo PIN',
      confirmNewPin:    'Confirmar novo PIN',
      pinResetSuccess:  'PIN atualizado ✅',
    },
    onboard: {
      welcomeTitle:        'Bem-vindo ao KEY Notes',
      welcomeDesc:         'Um arquivo privado e encriptado para contactos, links, notas e chaves — protegido com a tua própria frase-passe e PIN.',
      startBtn:            'Configurar agora',
      step1Title:          'Cria uma frase-passe principal',
      step1Desc:           'Esta é a verdadeira chave dos teus dados. Escolhe algo memorável — não há reposição. Guarda-a em local seguro.',
      passphraseLabel:     'Frase-passe principal',
      passphraseConfirm:   'Confirmar frase-passe',
      passphraseMismatch:  'As frases-passe não coincidem',
      passphraseTooShort:  'Usa pelo menos 10 caracteres',
      step2Title:          'Escolhe um PIN',
      step2Desc:           'Uma forma rápida de desbloquear diariamente.',
      pinConfirmTitle:     'Confirma o teu PIN',
      pinMismatch:         'Os PIN não coincidem — tenta novamente',
      step3Title:          'A tua chave de recuperação',
      step3Desc:           'Se um dia esqueceres o PIN e a frase-passe, este é o único caminho de volta. Guarda-a em local seguro.',
      recoveryConfirm:     'Guardei a minha chave de recuperação',
      emailLabel:          'Enviar cópia por email (opcional)',
      emailPh:             'tu@exemplo.com',
      emailSendBtn:        'Enviar-me uma cópia',
      emailSent:           'Chave de recuperação enviada ✅',
      emailFailed:         'Não foi possível enviar — guarda-a manualmente',
      finishBtn:           'Entrar no KEY Notes',
      continueBtn:         'Continuar',
      backBtn:             'Voltar',
    },
    panel: {
      title:        'Sobre o KEY Notes',
      tagline:      'O teu arquivo privado e encriptado.',
      desc:         'Contactos, links, notas e chaves — guardados localmente, encriptados com a tua própria frase-passe.',
      privacyTitle: 'Privacidade',
      privacyText:  'Sem servidor. Sem conta. Os teus dados nunca saem deste dispositivo, a menos que os exportes tu mesmo.',
    },
    tabs: {
      contacts: 'Contactos',
      links:    'Links',
      archive:  'Arquivo',
      keys:     'Chaves',
    },
    contacts: {
      title:          'Contactos',
      addBtn:         '+ Adicionar contacto',
      searchPh:       'Pesquisar contactos…',
      emptyState:     'Ainda sem contactos.',
      labelFirstName: 'Primeiro nome *',
      labelLastName:  'Apelido',
      labelBusiness:  'Empresa',
      labelPhones:    'Números de telefone',
      addPhoneBtn:    '+ Adicionar outro número',
      phoneLabelPh:   'Etiqueta (ex. Telemóvel, Trabalho)',
      phoneNumberPh:  'Número',
      labelEmail:     'Email',
      labelAddress:   'Morada',
      saveBtn:        'Guardar contacto',
      updateBtn:      'Atualizar contacto',
      toastSaved:     'Contacto guardado ✅',
      toastUpdated:   'Contacto atualizado ✅',
      toastDeleted:   'Contacto eliminado',
      toastNoName:    'Adiciona pelo menos um primeiro nome',
      confirmDelete:  'Eliminar este contacto?',
    },
    links: {
      title:               'Links',
      addBtn:              '+ Adicionar link',
      searchPh:            'Pesquisar links…',
      emptyState:          'Ainda sem links.',
      labelName:           'Nome *',
      labelUsername:       'Nome de utilizador',
      labelUrl:            'URL',
      labelPassword:       'Palavra-passe',
      showPassword:        'Mostrar',
      hidePassword:        'Ocultar',
      saveBtn:             'Guardar link',
      updateBtn:           'Atualizar link',
      toastSaved:          'Link guardado ✅',
      toastUpdated:        'Link atualizado ✅',
      toastDeleted:        'Link eliminado',
      toastNoName:         'Adiciona um nome',
      toastCopiedPassword: 'Palavra-passe copiada ✅',
      toastCopiedUsername: 'Nome de utilizador copiado ✅',
      confirmDelete:       'Eliminar este link?',
    },
    archive: {
      title:          'Arquivo',
      addBtn:         '+ Adicionar nota',
      searchPh:       'Pesquisar no arquivo…',
      emptyState:     'Ainda nada arquivado.',
      labelCategory:  'Categoria *',
      labelTitle:     'Título *',
      labelNote:      'Nota',
      notePh:         'Escreve livremente — este campo cresce com a tua nota…',
      saveBtn:        'Guardar nota',
      updateBtn:      'Atualizar nota',
      toastSaved:     'Nota guardada ✅',
      toastUpdated:   'Nota atualizada ✅',
      toastDeleted:   'Nota eliminada',
      toastNoTitle:   'Adiciona uma categoria e um título',
      confirmDelete:  'Eliminar esta nota?',
    },
    vaultKeys: {
      title:          'Chaves',
      addBtn:         '+ Adicionar chave',
      searchPh:       'Pesquisar chaves…',
      emptyState:     'Ainda sem chaves guardadas.',
      labelTitle:     'Título *',
      labelNote:      'Nota',
      notePh:         'Detalhes de licença, credenciais — tudo o que precises de ter à mão…',
      saveBtn:        'Guardar chave',
      updateBtn:      'Atualizar chave',
      toastSaved:     'Chave guardada ✅',
      toastUpdated:   'Chave atualizada ✅',
      toastDeleted:   'Chave eliminada',
      toastNoTitle:   'Adiciona um título',
      confirmDelete:  'Eliminar esta chave?',
    },
    common: {
      view: 'Ver', edit: 'Editar', copy: 'Copiar', save: 'Guardar',
      delete: 'Eliminar', close: 'Fechar', cancel: 'Cancelar',
      copiedGeneric: 'Copiado ✅',
    },
    settings: {
      title:               'Definições',
      backupTitle:         'Cópia de Segurança & Restauro',
      backupDesc:          'Os teus dados permanecem encriptados no ficheiro exportado — só pode ser aberto dentro do KEY Notes, com a tua frase-passe ou PIN.',
      downloadBtn:         'Descarregar cópia encriptada',
      restoreBtn:          'Restaurar a partir de cópia',
      toastDownloaded:     'Cópia encriptada descarregada ✅',
      toastRestored:       'Cópia restaurada ✅',
      toastRestoreFailed:  'Restauro falhou — verifica o ficheiro',
      securityTitle:       'Segurança',
      changePinBtn:        'Alterar PIN',
      changePassphraseBtn: 'Alterar frase-passe',
      viewRecoveryBtn:     'Gerar nova chave de recuperação',
      recoveryWarning:     'Isto substitui a tua chave antiga — a antiga deixará de funcionar.',
      lockNowBtn:          'Bloquear agora',
      langTitle:           'Idioma',
    },
    setup: {
      title:    'Sobre & FAQ',
      subtitle: 'Como o KEY Notes mantém o teu arquivo privado.',
      qaBtn:    'P & R',
      qaTitle:  'Perguntas & Respostas',
      closeBtn: 'Fechar',
      leaveBtn: 'Sair',
      qa: [
        { q: 'Onde são guardados os meus dados?',
          a: 'Inteiramente neste dispositivo, no armazenamento local do navegador — encriptados. Nada é enviado para um servidor.' },
        { q: 'O que acontece se eu esquecer o meu PIN?',
          a: 'Desbloqueia com a tua frase-passe e depois define um novo PIN nas Definições.' },
        { q: 'E se também esquecer a frase-passe?',
          a: 'Usa a tua chave de recuperação, mostrada uma única vez na configuração. Se também a perderes, os dados não podem ser recuperados.' },
        { q: 'Posso usar o KEY Notes em mais do que um dispositivo?',
          a: 'Cada dispositivo mantém os seus próprios dados encriptados. Usa Definições → Descarregar cópia encriptada, depois Restaurar no outro dispositivo.' },
        { q: 'O que significa "cópia encriptada"?',
          a: 'O ficheiro exportado é ilegível sem a tua frase-passe ou PIN.' },
        { q: 'Limpar os dados do navegador apaga tudo?',
          a: 'Sim, permanentemente. Descarrega uma cópia regularmente.' },
        { q: 'Boas práticas',
          a: 'Guarda a tua chave de recuperação fora deste dispositivo. Descarrega uma cópia após qualquer atualização importante.' },
      ],
    },
  },

}; // end translations
